// Curated emoji set for the ribbon icon picker — 8 categories, common
// finance/status/UI glyphs first. Hand-maintained (no build step; the
// full Unicode set would drown the picker). Each entry carries a
// searchable English `name` so the picker's search box matches on words
// ("fire", "check", "arrow") — not just a pasted glyph.

export interface EmojiEntry { readonly emoji: string; readonly name: string }

export const emojiCategories: ReadonlyArray<{ readonly category: string; readonly emojis: readonly EmojiEntry[] }> = [
  {
    category: 'Smileys',
    emojis: [
      { emoji: '😀', name: 'grinning face' },
      { emoji: '😃', name: 'smiley happy' },
      { emoji: '😄', name: 'smile happy' },
      { emoji: '😁', name: 'beaming grin' },
      { emoji: '😅', name: 'grinning sweat' },
      { emoji: '😂', name: 'laughing tears joy' },
      { emoji: '🙂', name: 'slight smile' },
      { emoji: '😉', name: 'wink' },
      { emoji: '😊', name: 'smiling blush' },
      { emoji: '😍', name: 'heart eyes love' },
      { emoji: '🤩', name: 'star struck' },
      { emoji: '😎', name: 'cool sunglasses' },
      { emoji: '🤔', name: 'thinking' },
      { emoji: '😐', name: 'neutral face' },
      { emoji: '😬', name: 'grimace' },
      { emoji: '🙄', name: 'rolling eyes' },
      { emoji: '😴', name: 'sleeping sleep' },
      { emoji: '🤯', name: 'mind blown exploding head' },
      { emoji: '😱', name: 'scream fear' },
      { emoji: '😢', name: 'crying sad' },
      { emoji: '😡', name: 'angry rage' },
      { emoji: '🥳', name: 'party celebrate' },
      { emoji: '🤗', name: 'hug' },
      { emoji: '🫡', name: 'salute' },
    ],
  },
  {
    category: 'Gestures & People',
    emojis: [
      { emoji: '👍', name: 'thumbs up like approve' },
      { emoji: '👎', name: 'thumbs down dislike' },
      { emoji: '👌', name: 'ok hand' },
      { emoji: '✌️', name: 'victory peace' },
      { emoji: '🤞', name: 'fingers crossed luck' },
      { emoji: '👏', name: 'clap applause' },
      { emoji: '🙌', name: 'raising hands celebrate' },
      { emoji: '🤝', name: 'handshake deal' },
      { emoji: '💪', name: 'muscle strong' },
      { emoji: '🫵', name: 'pointing you' },
      { emoji: '👉', name: 'point right' },
      { emoji: '👈', name: 'point left' },
      { emoji: '👆', name: 'point up' },
      { emoji: '👇', name: 'point down' },
      { emoji: '✋', name: 'raised hand stop' },
      { emoji: '🖐️', name: 'hand fingers splayed' },
      { emoji: '👋', name: 'wave hello' },
      { emoji: '🤙', name: 'call me hand' },
      { emoji: '🙏', name: 'pray thanks please' },
      { emoji: '💁', name: 'information desk person' },
      { emoji: '🙋', name: 'raising hand question' },
      { emoji: '🤷', name: 'shrug' },
      { emoji: '🏃', name: 'running run' },
      { emoji: '🧍', name: 'standing person' },
    ],
  },
  {
    category: 'Arrows',
    emojis: [
      { emoji: '⬆️', name: 'arrow up' },
      { emoji: '⬇️', name: 'arrow down' },
      { emoji: '⬅️', name: 'arrow left' },
      { emoji: '➡️', name: 'arrow right' },
      { emoji: '↗️', name: 'arrow up right' },
      { emoji: '↘️', name: 'arrow down right' },
      { emoji: '↙️', name: 'arrow down left' },
      { emoji: '↖️', name: 'arrow up left' },
      { emoji: '↕️', name: 'arrow up down' },
      { emoji: '↔️', name: 'arrow left right' },
      { emoji: '↩️', name: 'arrow back return' },
      { emoji: '↪️', name: 'arrow forward' },
      { emoji: '⤴️', name: 'arrow curve up' },
      { emoji: '⤵️', name: 'arrow curve down' },
      { emoji: '🔼', name: 'up button triangle' },
      { emoji: '🔽', name: 'down button triangle' },
      { emoji: '⏫', name: 'fast up double arrow' },
      { emoji: '⏬', name: 'fast down double arrow' },
      { emoji: '🔄', name: 'refresh reload sync' },
      { emoji: '🔁', name: 'repeat loop' },
      { emoji: '🔀', name: 'shuffle random' },
      { emoji: '◀️', name: 'reverse play left' },
      { emoji: '▶️', name: 'play right' },
      { emoji: '⏸️', name: 'pause' },
    ],
  },
  {
    category: 'Symbols & Status',
    emojis: [
      { emoji: '✅', name: 'check mark tick done success' },
      { emoji: '❌', name: 'cross wrong error fail' },
      { emoji: '⚠️', name: 'warning caution alert' },
      { emoji: '❗', name: 'exclamation important' },
      { emoji: '❓', name: 'question help' },
      { emoji: '💯', name: 'hundred percent perfect' },
      { emoji: '🔴', name: 'red circle' },
      { emoji: '🟠', name: 'orange circle' },
      { emoji: '🟡', name: 'yellow circle' },
      { emoji: '🟢', name: 'green circle' },
      { emoji: '🔵', name: 'blue circle' },
      { emoji: '🟣', name: 'purple circle' },
      { emoji: '⚫', name: 'black circle' },
      { emoji: '⚪', name: 'white circle' },
      { emoji: '🟥', name: 'red square' },
      { emoji: '🟧', name: 'orange square' },
      { emoji: '🟨', name: 'yellow square' },
      { emoji: '🟩', name: 'green square' },
      { emoji: '🟦', name: 'blue square' },
      { emoji: '🟪', name: 'purple square' },
      { emoji: '⭐', name: 'star favorite' },
      { emoji: '🌟', name: 'glowing star sparkle' },
      { emoji: '✨', name: 'sparkles' },
      { emoji: '🚫', name: 'prohibited no forbidden' },
    ],
  },
  {
    category: 'Finance',
    emojis: [
      { emoji: '💰', name: 'money bag' },
      { emoji: '💵', name: 'dollar banknote' },
      { emoji: '💴', name: 'yen banknote' },
      { emoji: '💶', name: 'euro banknote' },
      { emoji: '💷', name: 'pound banknote' },
      { emoji: '💸', name: 'money flying spend' },
      { emoji: '💳', name: 'credit card' },
      { emoji: '🪙', name: 'coin' },
      { emoji: '🏦', name: 'bank' },
      { emoji: '📈', name: 'chart up trend increase' },
      { emoji: '📉', name: 'chart down trend decrease' },
      { emoji: '📊', name: 'bar chart' },
      { emoji: '🧾', name: 'receipt invoice' },
      { emoji: '💹', name: 'chart yen up' },
      { emoji: '🤑', name: 'money mouth rich' },
      { emoji: '🏧', name: 'atm cash machine' },
      { emoji: '💲', name: 'dollar sign' },
      { emoji: '🛒', name: 'shopping cart' },
      { emoji: '🛍️', name: 'shopping bags' },
      { emoji: '📦', name: 'package box' },
      { emoji: '🏷️', name: 'label price tag' },
      { emoji: '⚖️', name: 'balance scale' },
      { emoji: '🗃️', name: 'card file box archive' },
      { emoji: '💼', name: 'briefcase business' },
    ],
  },
  {
    category: 'Objects & Tech',
    emojis: [
      { emoji: '💻', name: 'laptop computer' },
      { emoji: '🖥️', name: 'desktop computer monitor' },
      { emoji: '⌨️', name: 'keyboard' },
      { emoji: '🖱️', name: 'mouse' },
      { emoji: '📱', name: 'phone mobile smartphone' },
      { emoji: '☎️', name: 'telephone phone' },
      { emoji: '🖨️', name: 'printer' },
      { emoji: '💾', name: 'floppy disk save' },
      { emoji: '📡', name: 'satellite antenna signal' },
      { emoji: '🔋', name: 'battery' },
      { emoji: '🔌', name: 'plug power' },
      { emoji: '💡', name: 'light bulb idea' },
      { emoji: '🔦', name: 'flashlight torch' },
      { emoji: '🔧', name: 'wrench tool' },
      { emoji: '🔨', name: 'hammer' },
      { emoji: '⚙️', name: 'gear settings cog' },
      { emoji: '🧲', name: 'magnet' },
      { emoji: '🔒', name: 'lock closed secure' },
      { emoji: '🔓', name: 'unlock open' },
      { emoji: '🔑', name: 'key' },
      { emoji: '📌', name: 'pushpin pin' },
      { emoji: '📎', name: 'paperclip attach' },
      { emoji: '✂️', name: 'scissors cut' },
      { emoji: '🗑️', name: 'trash delete wastebasket' },
    ],
  },
  {
    category: 'Time & Weather',
    emojis: [
      { emoji: '⏰', name: 'alarm clock' },
      { emoji: '⏱️', name: 'stopwatch timer' },
      { emoji: '⏳', name: 'hourglass time' },
      { emoji: '⌛', name: 'hourglass done' },
      { emoji: '🕐', name: 'clock time' },
      { emoji: '📅', name: 'calendar date' },
      { emoji: '🗓️', name: 'calendar spiral schedule' },
      { emoji: '☀️', name: 'sun sunny' },
      { emoji: '🌤️', name: 'sun behind cloud' },
      { emoji: '⛅', name: 'partly cloudy' },
      { emoji: '🌧️', name: 'rain cloud' },
      { emoji: '⛈️', name: 'storm thunder rain' },
      { emoji: '🌩️', name: 'lightning cloud' },
      { emoji: '❄️', name: 'snowflake cold snow' },
      { emoji: '🌪️', name: 'tornado' },
      { emoji: '🌈', name: 'rainbow' },
      { emoji: '🌙', name: 'moon night crescent' },
      { emoji: '🌡️', name: 'thermometer temperature' },
      { emoji: '💧', name: 'droplet water drop' },
      { emoji: '🔥', name: 'fire flame hot' },
      { emoji: '⚡', name: 'lightning bolt electric zap' },
      { emoji: '🌊', name: 'wave water ocean' },
      { emoji: '🌍', name: 'globe earth world' },
      { emoji: '🪐', name: 'planet saturn' },
    ],
  },
  {
    category: 'Nature & Food',
    emojis: [
      { emoji: '🌱', name: 'seedling sprout plant grow' },
      { emoji: '🌿', name: 'herb leaf' },
      { emoji: '🍀', name: 'clover luck' },
      { emoji: '🌲', name: 'evergreen tree' },
      { emoji: '🌴', name: 'palm tree' },
      { emoji: '🌸', name: 'blossom flower cherry' },
      { emoji: '🌻', name: 'sunflower flower' },
      { emoji: '🍎', name: 'apple fruit red' },
      { emoji: '🍊', name: 'orange fruit tangerine' },
      { emoji: '🍋', name: 'lemon fruit' },
      { emoji: '🍇', name: 'grapes fruit' },
      { emoji: '🍓', name: 'strawberry fruit' },
      { emoji: '🥑', name: 'avocado' },
      { emoji: '🍕', name: 'pizza food' },
      { emoji: '🍔', name: 'burger hamburger food' },
      { emoji: '☕', name: 'coffee hot drink' },
      { emoji: '🍺', name: 'beer drink' },
      { emoji: '🐝', name: 'bee insect' },
      { emoji: '🦋', name: 'butterfly' },
      { emoji: '🐟', name: 'fish' },
      { emoji: '🐢', name: 'turtle tortoise' },
      { emoji: '🦅', name: 'eagle bird' },
      { emoji: '🐘', name: 'elephant' },
      { emoji: '🦁', name: 'lion' },
    ],
  },
];
